version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: apitest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db_initializer:
    build:
      context: ./api_async
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_USER: pgadmin
      DB_PASSWORD: pgadmin
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: apitest

  web:
    build:
      context: ./api_async
      dockerfile: Dockerfile.fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api_async:/app
    depends_on:
      - db_initializer
    environment:
      DATABASE_URL: postgres://pgadmin:pgadmin@db:5432/apitest

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
